include:
  - project: cta-computing/common/aiv-toolkit
    ref: 73f6fb0f6e3df76a825ab082d77f656fe8de6c96
    file: ci-functions.yml
  - aiv-config.yml


stages:
  - prepare
  - lint
  - build
  - sign
  - tests
  - sonarqube
  - publish
  - report
  - changelog

build-docs:
  rules:
    - when: never

deploy_docs_env:
  rules:
    - when: never

pages:
  stage: publish
  before_script:
  - pip install -r requirements-docs.txt
  script:
  - mkdocs build --strict --site-dir public
  artifacts:
    paths: [public]
