include:
  - project: cta-computing/common/aiv-toolkit
    ref: e78b620a2db2be7f6177c6ee3b2a8bf35c781093
    file: ci-functions.yml
  - aiv-config.yml

stages:
  - prepare
  - lint
  - build
  - sign
  - tests
  - sonarqube
  - publish
  - report
  - changelog
  - build-sonar

build:
  tags:
    - desy-test-cluster
  parallel:
    matrix:
      - IMAGE: ["frontend", "backend", "auth", "playwright"]
  variables:
    CI_HARBOR_REGISTRY_IMAGE: harbor.cta-observatory.org/suss/${CI_PROJECT_NAME}-${IMAGE}:${DOCKER_TAG}
    AIV_DOCKER_IMAGE_CONTEXT: $CI_PROJECT_DIR
    AIV_DOCKERFILE: Dockerfile.${IMAGE}
    DOCKER_CONFIG: /kaniko/.docker
    KUBERNETES_CPU_REQUEST: "1"
    KUBERNETES_CPU_LIMIT: "2"
    KUBERNETES_MEMORY_REQUEST: "16Gi"
    KUBERNETES_MEMORY_LIMIT: "64Gi"

unit-test:
  stage: tests
  image: ghcr.io/prefix-dev/pixi:latest
  script:
    - pixi run test
  artifacts:
    paths:
      - test/coverage.xml
      - test/report.xml

frontend-test:
  stage: tests
  image: harbor.cta-observatory.org/proxy_cache/node:24.2-alpine
  cache:
    key:
      files:
        - js/package-lock.json
    paths:
      - js/node_modules/
  before_script:
    - npm ci --prefix js
  script:
    - CI=true npm test --prefix js -- --watchAll=false --coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d.]+)/'
  artifacts:
    when: always
    paths:
      - js/coverage/
    expire_in: 1 week

k8s-integration-tests:
  tags:
    - desy-testcluster-ctao-computing-aiv
  artifacts:
    when: always
    paths:
      - test-in-k8s/
      - .toolkit/stats/pull-images-statistics.json
      - .toolkit/stats/testkit-helm-upgrade-statistics.json
      - test_frontend_screenshot_1_before.png
      - test_frontend_screenshot_2_resolve.png
      - test_frontend_screenshot_3_search.png
    expose_as: "K8s Integration Test Results"
    reports:
      junit: test-in-k8s/report.xml

k8s-upgrade-integration-tests:
  extends: .test-in-k8s
  tags:
    - desy-testcluster-ctao-computing-aiv
  variables:
    UPGRADE_BASE_REF: "v0.9.2"

build-docs:
  rules:
    - when: never

deploy_docs_env:
  rules:
    - when: never

pypi:
  rules:
    - when: never

pages:
  stage: publish
  needs: []
  before_script:
    - pip install -r requirements-docs.txt
  script:
    - mkdocs build --strict --site-dir public
  artifacts:
    paths:
      - public