include:
  - project: cta-computing/common/aiv-toolkit
    ref: 853426fd8b994cd570a046238226424a9c18aedf
    file: ci-functions.yml
  - aiv-config.yml


stages:
  - prepare
  - lint
  - build
  - sign
  - tests
  - sonarqube
  - publish
  - report
  - changelog

build:
  retry: 2
  parallel:
    matrix:
      - IMAGE: ["frontend", "backend"]

  variables:
    CI_HARBOR_REGISTRY_IMAGE: 
      harbor.cta-observatory.org/suss/${CI_PROJECT_NAME}-${IMAGE}:${DOCKER_TAG}
    AIV_DOCKER_FILE: Dockerfile.${IMAGE}
    DOCKER_CONFIG: /kaniko/.docker



build-docs:
  rules:
    - when: never

deploy_docs_env:
  rules:
    - when: never

pages:
  stage: publish
  before_script:
    - pip install -r requirements-docs.txt
  script:
    - mkdocs build --strict --site-dir public
  artifacts:
    paths: [public]
