# TODO: we might want to add more hooks following CTAO computing software standards


repos:
  - repo: 
      https://gitlab.cta-observatory.org/cta-computing/common/aiv-toolkit.git
    rev: v4.0.1
    hooks:
      - id: ctao-aiv-toolkit
