variables:
  # used to select UCs and Requirements from release plan
  SYSTEM: SUSS
  APPLICATION_NAME: ctao-data-explorer
  APPLICATION_AUTHOR: ctao-data-explorer Team
  APPLICATION_AUTHOR_ORGANIZATION: CTAO

  # for publishing images and charts
  HARBOR_PROJECT: suss
  HARBOR_PROJECT_ID: 10

  RELEASE: v0.1.0
  RELEASE_PLAN_FROM_JAMA: false
  UC_GROUPS: SAT
  RELEASE_PLAN_FN: https://gitlab.cta-observatory.org/cta-computing/suss/suss-project-management/suss-release-plan/-/raw/main/release_development_document/suss-release-plan.tex?ref_type=heads
  TRACEABILITY_CSV_FN: https://gitlab.cta-observatory.org/cta-computing/suss/suss-project-management/requirements-traceability/-/raw/main/SUSS_Requirements_Traceability_Matrix.csv?ref_type=heads

  DOCKER_IMAGE_CONTEXT: .

  SONAR_PROJECT_KEY: 
  SONAR_BRANCH: main

  CHART_LOCATION: chart

  ENABLE_INGRESS: true

  ALLOWED_IMAGE_PREFIXES: docker,postgres,redis,registry.k8s.io
