
FROM ghcr.io/prefix-dev/pixi:latest AS auth

RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

COPY pixi.* /app/
COPY auth_service /app/auth_service
COPY ctao_shared /app/ctao_shared

WORKDIR /app

RUN pixi install
WORKDIR /app/auth_service

EXPOSE 8001

CMD ["pixi", "run", "auth-serve"]
