
FROM harbor.cta-observatory.org/proxy_cache/ubuntu:24.04

RUN apt-get update && apt-get install -y curl dnsutils python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean && \
    python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --upgrade pip setuptools && \
    pip install --upgrade  \
        coverage \
        playwright \
        pytest \
        pytest-cov \
        pytest-playwright  \
        pytest-requirements \
        requests && \
    playwright install firefox && \
    playwright install-deps firefox && \
    mv /root/.cache/ms-playwright /opt/ms-playwright && \
    chmod -R a+rX /opt/ms-playwright

ENV PLAYWRIGHT_BROWSERS_PATH=/opt/ms-playwright
