
FROM ghcr.io/prefix-dev/pixi:0.67.2-noble AS auth

RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

COPY pixi.* /app/
COPY auth_service /app/auth_service
COPY ctao_shared /app/ctao_shared

WORKDIR /app

RUN pixi install \
    && useradd --create-home --shell /bin/bash appuser \
    && chown -R appuser:appuser /app

USER appuser

WORKDIR /app/auth_service

EXPOSE 8001

CMD ["pixi", "run", "auth-serve"]
