# Backend (FastAPI)
#FROM harbor.cta-observatory.org/proxy_cache/python:3.13.3 AS backend
FROM ghcr.io/prefix-dev/pixi:latest AS backend

# System dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev gcc && \
    rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app

# Install dependencies
RUN pixi install

WORKDIR /app/api

# FastAPI port
EXPOSE 8000

# Run uvicorn (reloaded in dev) see definition in pixi tasks
CMD ["pixi", "run", "serve-reload"]
