site_name: CTAO Data Explorer
site_description: "Portal to access, visualize, and analyze high-energy astrophysics data"
site_url: ""
repo_name: aopy/ctao-data-explorer
repo_url: https://github.com/aopy/ctao-data-explorer
edit_uri: ""

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.tooltips
    - search.suggest
    - search.highlight
  language: en

nav:
  - Overview: index.md
  - User Guide:
    - Searching Data: user-guide/search.md
    - Exploring Results: user-guide/results.md
    - Baskets & Preview Jobs: user-guide/baskets-and-jobs.md
    - Sign-in & Profiles: user-guide/auth.md
  - Developer Guide:
    - Architecture: developer-guide/architecture.md
    - Configuration (.env): developer-guide/configuration.md
    - API & OpenAPI: developer-guide/api.md
    - Deployment: developer-guide/deployment.md
    - CI/CD for Docs: developer-guide/ci-cd.md
    - Standards & Interop: developer-guide/standards.md
    - Metrics & Health: developer-guide/metrics.md
    - Security Notes: developer-guide/security.md
  - Admin:
    - Operations & Maintenance: admin/maintenance.md
    - Troubleshooting: admin/troubleshooting.md
  - Release Notes: release-notes.md
  - Credits: credits.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aopy/ctao-data-explorer