[workspace]
name = "ctao-data-explorer-backend"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = "3.12.*"
fastapi = "0.115.*"
fastapi-users = "15.0.*"
fastapi-users-db-sqlalchemy = "*"
uvicorn = "0.32.*"
aiofiles = "22.1.*"
pyvo = "1.*"
numpy = "2.1.*"
requests = "2.32.*"
cryptography = ">=46.0.5,<47"
hiredis = "3.2.*"
authlib = "1.4.*"
itsdangerous = "*"
asyncpg = "*"
httpx = "0.28.*"
xmltodict = "1.0.*"
alembic = "1.14.*"
psycopg2 = "*"
libpq = "*"
astropy = "6.1.*"
pydantic = "2.9.*"
anyio = "4.4.*"
python-dotenv = "*"
redis-py = "*"
pydantic-settings = "*"
prometheus-fastapi-instrumentator = "*"
asgi-lifespan = ">=2.1.0,<3"
aiosqlite = ">=0.22.1,<0.23"


[tasks]
migrate = "alembic upgrade head"
serve = "uvicorn api.main:app --host 0.0.0.0 --port 8000"
auth-serve = "uvicorn auth_service.main:app --host 0.0.0.0 --port 8001"
serve-reload = "uvicorn api.main:app --reload --host 0.0.0.0 --port 8000"
build-frontend = "bash -lc 'cd js && npm ci && npm run build'"

[feature.test.dependencies]
pytest = "*"
pytest-cov = "*"

[feature.test.tasks]
test = "pytest"

[environments]
test = ["test"]
