[pytest]
addopts =
    -ra
    -v
    --color=yes
    --cov
    --cov-report=xml:test/coverage.xml
    --junitxml=test/report.xml
    --log-cli-level=INFO
asyncio_mode = auto
testpaths = api/tests auth_service/tests
filterwarnings =
    ignore::DeprecationWarning