# CTAO canonical Sonar settings.
sonar.projectKey=cta-computing_suss_scienceportal_prototypes_ctao-data-explorer_f2a3a158-f5a7-4f1f-a8f9-78feed28938c
sonar.host.url=https://sonar-ctao.zeuthen.desy.de

sonar.qualitygate.wait=true

sonar.sources=api,auth_service,download_service,js/src
sonar.tests=api/tests,auth_service/tests,download_service/tests,tests

# Exclusions
sonar.exclusions=api/tests/**,auth_service/tests/**,download_service/tests/**,aiv-toolkit/**,js/node_modules/**,js/build/**,js/public/**,js/__mocks__/**,node_modules/**,docs/_build/**,alembic/versions/**
sonar.coverage.exclusions=**/tests/**,**/__tests__/**
sonar.cpd.exclusions=**/tests/**,**/__tests__/**

# Python configuration
sonar.python.coverage.reportPaths=test/coverage.xml
sonar.python.version=3.12

# JavaScript configuration
sonar.javascript.lcov.reportPaths=js/coverage/lcov.info
