# CTAO canonical Sonar settings.
sonar.projectKey=cta-computing_suss_scienceportal_prototypes_ctao-data-explorer_f2a3a158-f5a7-4f1f-a8f9-78feed28938c
sonar.host.url=https://sonar-ctao.zeuthen.desy.de

sonar.qualitygate.wait=true
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

sonar.exclusions=aiv-toolkit/**,js/**,node_modules/**,docs/_build/**,alembic/versions/**,tests/**