# CTAO canonical Sonar settings.
sonar.projectKey=cta-computing_suss_scienceportal_prototypes_ctao-data-explorer_f2a3a158-f5a7-4f1f-a8f9-78feed28938c
sonar.host.url=https://sonar-ctao.zeuthen.desy.de

sonar.qualitygate.wait=true

sonar.sources=.
sonar.inclusions=api/**,auth_service/**,ctao_shared/**,download_service/**,js/src/**,chart/**,Dockerfile.*

sonar.tests=api/tests,auth_service/tests,download_service/tests,tests,js/src
sonar.test.inclusions=js/src/**/*.test.js,js/src/**/*.spec.js

# Exclusions from source analysis, coverage and duplication detection
sonar.exclusions=api/tests/**,auth_service/tests/**,download_service/tests/**,js/src/**/*.test.js,js/src/**/*.spec.js,aiv-toolkit/**,chart/charts/**,js/node_modules/**,js/build/**,js/public/**,js/__mocks__/**,node_modules/**,alembic/versions/**
sonar.coverage.exclusions=**/tests/**,js/src/**/*.test.js,js/src/**/*.spec.js,js/src/setupTests.js
sonar.cpd.exclusions=**/tests/**

# Python configuration
sonar.python.coverage.reportPaths=test/coverage.xml
sonar.python.version=3.12

# JavaScript configuration
sonar.javascript.lcov.reportPaths=js/coverage/lcov.info

# Kubernetes / Helm settings
sonar.kubernetes.activate=true
sonar.kubernetes.helm.activate=true
