{{- if not .Values.auth.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctao-data-explorer.fullname" . }}-auth-secrets
  labels:
    {{- include "ctao-data-explorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  CTAO_CLIENT_ID: {{ .Values.auth.secrets.clientId | quote }}
  CTAO_CLIENT_SECRET: {{ .Values.auth.secrets.clientSecret | quote }}
  REFRESH_TOKEN_ENCRYPTION_KEY: {{ .Values.auth.secrets.refreshTokenEncryptionKey | quote }}
  SESSION_SECRET_KEY_OIDC: {{ .Values.auth.secrets.sessionSecretKeyOidc | quote }}
{{- end }}