{{- if and .Values.download.enabled (not .Values.download.secrets.existingSecret) }}
{{- $clientId := required "download.secrets.clientId is required" .Values.download.secrets.clientId }}
{{- $clientSecret := required "download.secrets.clientSecret is required" .Values.download.secrets.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ctao-data-explorer.fullname" . }}-download-secrets
  labels:
    {{- include "ctao-data-explorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DOWNLOAD_SERVICE_CLIENT_ID: {{ $clientId | quote }}
  DOWNLOAD_SERVICE_CLIENT_SECRET: {{ $clientSecret | quote }}
{{- end }}
