{{- if and .Values.iam.enabled .Values.iam.ingress.tls.enabled }}
{{- $ca := genCA "iam-ca" 365 }}
{{- $cert := genSignedCert "iam-ctao-data-explorer.test.example" nil (list "iam-ctao-data-explorer.test.example") 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.iam.ingress.tls.secretName }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: ctao-data-explorer
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
