{{- if and .Values.iam.enabled (not .Values.iam.vomsAA.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-iam-voms-lsc
  labels:
    app.kubernetes.io/name: indigo-iam
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  ctao.test: ""
{{- end }}
