{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ctao-data-explorer.fullname" . }}-redis-master
  labels:
    {{- include "ctao-data-explorer.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "ctao-data-explorer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
