{{- if and .Values.dev.run_tests .Values.tests.existingSecret }}
{{- else if and .Values.dev.run_tests .Values.tests.testUser .Values.tests.testPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: ctao-data-explorer
type: Opaque
stringData:
  testUser: {{ .Values.tests.testUser | quote }}
  testPassword: {{ .Values.tests.testPassword | quote }}
{{- end }}
