"""Make basket_id nullable fix

Revision ID: 4f07440fb4c8
Revises: b5681a010c12
Create Date: 2025-03-07 17:23:11.873188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f07440fb4c8'
down_revision: Union[str, None] = 'b5681a010c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
