"""Add baskets

Revision ID: 59e2d2f939df
Revises: fe3ab8ddfbef
Create Date: 2025-03-07 15:19:01.026489

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "59e2d2f939df"
down_revision: Union[str, None] = "fe3ab8ddfbef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "saved_datasets", "basket_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_index("ix_saved_datasets_basket_id", table_name="saved_datasets")
    op.drop_column("users", "first_login_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "first_login_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_saved_datasets_basket_id", "saved_datasets", ["basket_id"], unique=False
    )
    op.alter_column(
        "saved_datasets", "basket_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
