"""add adql_query_hash column

Revision ID: 6b29f4007a05
Revises: 9e75aca1baff
Create Date: 2025-04-15 17:13:46.886459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b29f4007a05'
down_revision: Union[str, None] = '9e75aca1baff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_history', sa.Column('adql_query_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_query_history_adql_query_hash'), 'query_history', ['adql_query_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_query_history_adql_query_hash'), table_name='query_history')
    op.drop_column('query_history', 'adql_query_hash')
    # ### end Alembic commands ###
