"""add query_history

Revision ID: 6f1e07f959d5
Revises: 570e28316e72
Create Date: 2025-03-13 15:23:38.707385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6f1e07f959d5"
down_revision: Union[str, None] = "570e28316e72"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "query_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("query_params", sa.Text(), nullable=True),
        sa.Column("results", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_query_history_id"), "query_history", ["id"], unique=False)
    op.drop_index("ix_saved_datasets_basket_id", table_name="saved_datasets")
    op.drop_index("ix_saved_datasets_id", table_name="saved_datasets")
    op.drop_constraint(
        "saved_datasets_user_id_fkey", "saved_datasets", type_="foreignkey"
    )
    op.create_foreign_key(None, "saved_datasets", "users", ["user_id"], ["id"])
    op.drop_column("saved_datasets", "basket_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saved_datasets",
        sa.Column("basket_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "saved_datasets", type_="foreignkey")
    op.create_foreign_key(
        "saved_datasets_user_id_fkey",
        "saved_datasets",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_index("ix_saved_datasets_id", "saved_datasets", ["id"], unique=False)
    op.create_index(
        "ix_saved_datasets_basket_id", "saved_datasets", ["basket_id"], unique=False
    )
    op.drop_index(op.f("ix_query_history_id"), table_name="query_history")
    op.drop_table("query_history")
    # ### end Alembic commands ###
