"""add first_login_at to users

Revision ID: 7172e1edf598
Revises: 236c56bcb776
Create Date: 2025-01-29 15:05:48.961841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7172e1edf598"
down_revision: Union[str, None] = "236c56bcb776"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("first_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_login_at")
    # ### end Alembic commands ###
