"""Add saved_baskets

Revision ID: 8571a003b64a
Revises: ccc2f746a79a
Create Date: 2025-03-06 14:26:28.542871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8571a003b64a"
down_revision: Union[str, None] = "ccc2f746a79a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_baskets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_saved_baskets_id"), "saved_baskets", ["id"], unique=False)
    op.create_index(
        op.f("ix_saved_baskets_user_id"), "saved_baskets", ["user_id"], unique=False
    )
    op.add_column(
        "saved_datasets", sa.Column("basket_id", sa.Integer(), nullable=False)
    )
    op.create_index(
        op.f("ix_saved_datasets_basket_id"),
        "saved_datasets",
        ["basket_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_saved_datasets_id"), "saved_datasets", ["id"], unique=False
    )
    op.drop_constraint(
        "saved_datasets_user_id_fkey", "saved_datasets", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "saved_datasets", "saved_baskets", ["basket_id"], ["id"]
    )
    op.drop_column("saved_datasets", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "saved_datasets",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "saved_datasets", type_="foreignkey")
    op.create_foreign_key(
        "saved_datasets_user_id_fkey", "saved_datasets", "users", ["user_id"], ["id"]
    )
    op.drop_index(op.f("ix_saved_datasets_id"), table_name="saved_datasets")
    op.drop_index(op.f("ix_saved_datasets_basket_id"), table_name="saved_datasets")
    op.drop_column("saved_datasets", "basket_id")
    op.drop_index(op.f("ix_saved_baskets_user_id"), table_name="saved_baskets")
    op.drop_index(op.f("ix_saved_baskets_id"), table_name="saved_baskets")
    op.drop_table("saved_baskets")
    # ### end Alembic commands ###
