"""drop adql_query_hash column

Revision ID: 9c512b145f88
Revises: cc0837c676f3
Create Date: 2025-07-09 14:28:14.791355

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c512b145f88"
down_revision: Union[str, None] = "cc0837c676f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_query_history_adql_query_hash", table_name="query_history")
    op.drop_column("query_history", "adql_query_hash")
    op.drop_index("ix_user_refresh_tokens_user_id", table_name="user_refresh_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_user_refresh_tokens_user_id",
        "user_refresh_tokens",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "query_history",
        sa.Column("adql_query_hash", sa.String(length=64), nullable=True, index=True),
    )
    op.create_index(
        "ix_query_history_adql_query_hash",
        "query_history",
        ["adql_query_hash"],
        unique=False,
    )
    # ### end Alembic commands ###
