"""add basket_items_association

Revision ID: 9e75aca1baff
Revises: 6f1e07f959d5
Create Date: 2025-04-07 15:59:00.635982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e75aca1baff'
down_revision: Union[str, None] = '6f1e07f959d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_items_association',
    sa.Column('basket_group_id', sa.Integer(), nullable=False),
    sa.Column('saved_dataset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basket_group_id'], ['basket_groups.id'], ),
    sa.ForeignKeyConstraint(['saved_dataset_id'], ['saved_datasets.id'], ),
    sa.PrimaryKeyConstraint('basket_group_id', 'saved_dataset_id')
    )
    op.drop_constraint('saved_datasets_basket_group_id_fkey', 'saved_datasets', type_='foreignkey')
    op.drop_column('saved_datasets', 'basket_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_datasets', sa.Column('basket_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('saved_datasets_basket_group_id_fkey', 'saved_datasets', 'basket_groups', ['basket_group_id'], ['id'])
    op.drop_table('basket_items_association')
    # ### end Alembic commands ###
