"""Make basket_id nullable

Revision ID: b5681a010c12
Revises: ccd188f1af04
Create Date: 2025-03-07 17:08:25.530276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5681a010c12'
down_revision: Union[str, None] = 'ccd188f1af04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_datasets', 'basket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('saved_datasets', 'basket_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
