"""add opus token table

Revision ID: c296416b08f5
Revises: 9c512b145f88
Create Date: 2025-09-23 14:24:04.050125

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c296416b08f5"
down_revision: Union[str, None] = "9c512b145f88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "external_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_encrypted", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "service"),
    )
    op.create_index(
        op.f("ix_external_tokens_service"), "external_tokens", ["service"], unique=False
    )
    op.create_index(
        op.f("ix_external_tokens_user_id"), "external_tokens", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_external_tokens_user_id"), table_name="external_tokens")
    op.drop_index(op.f("ix_external_tokens_service"), table_name="external_tokens")
    op.drop_table("external_tokens")
    # ### end Alembic commands ###
