"""Add baskets fix

Revision ID: ccd188f1af04
Revises: 59e2d2f939df
Create Date: 2025-03-07 15:27:43.535270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ccd188f1af04"
down_revision: Union[str, None] = "59e2d2f939df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("saved_datasets", "basket_id", existing_type=sa.INTEGER(), nullable=False)
    op.create_index(
        op.f("ix_saved_datasets_basket_id"),
        "saved_datasets",
        ["basket_id"],
        unique=False,
    )
    op.add_column("users", sa.Column("first_login_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "first_login_at")
    op.drop_index(op.f("ix_saved_datasets_basket_id"), table_name="saved_datasets")
    op.alter_column("saved_datasets", "basket_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
