"""drop user_refresh_tokens

Revision ID: ccf858918774
Revises: b629e9127982
Create Date: 2026-03-09 16:43:34.193426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ccf858918774"
down_revision: Union[str, None] = "b629e9127982"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_refresh_tokens_id", table_name="user_refresh_tokens")
    op.drop_table("user_refresh_tokens")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_refresh_tokens",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "iam_provider_name",
            sa.VARCHAR(),
            server_default=sa.text("'ctao'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("encrypted_refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_used_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_refresh_tokens_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="user_refresh_tokens_pkey"),
    )
    op.create_index("ix_user_refresh_tokens_id", "user_refresh_tokens", ["id"], unique=False)
    # ### end Alembic commands ###
