---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gcert-ca-requests.aiv.ctao.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: aiv.ctao.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretNames:
                  type: array
                  items:
                    type: string
                certKey:
                  type: string
                  default: tls.crt
                keyKey:
                  type: string
                  default: tls.key
                certkeyKey:
                  type: string
                proxyKey:
                  type: string
                crlKey:
                  type: string
              required: ["secretNames"]



  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gcert-ca-requests
    # singular name to be used as an alias on the CLI and for display
    singular: gcert-ca-request
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GCertCARequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gcrqca
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gcert-server-requests.aiv.ctao.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: aiv.ctao.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretNames:
                  type: array
                  items:
                    type: string
                dn:
                  type: string
                serverNames:
                  type: array
                  items:
                    type: string
                certKey:
                  type: string
                  default: tls.crt
                keyKey:
                  type: string
                  default: tls.key
                certkeyKey:
                  type: string
              required: ["secretNames"]

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gcert-server-requests
    # singular name to be used as an alias on the CLI and for display
    singular: gcert-server-request
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GCertServerRequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gcrqs
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gcert-ssh-requests.aiv.ctao.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: aiv.ctao.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretNames:
                  type: array
                  items:
                    type: string
                publickeyKey:
                  type: string
                privatekeyKey:
                  type: string
              required: ["secretNames"]


  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gcert-ssh-requests
    # singular name to be used as an alias on the CLI and for display
    singular: gcert-ssh-request
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GCertSSHRequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gcrqssh
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: gcert-user-requests.aiv.ctao.org
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: aiv.ctao.org
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretNames:
                  type: array
                  items:
                    type: string
                dn:
                  type: string
                email:
                  type: string
                certKey:
                  type: string
                  default: tls.crt
                keyKey:
                  type: string
                  default: tls.key
                certkeyKey:
                  type: string
                  default: tls.certkey
                proxyKey:
                  type: string
                  default: tls.proxy
              required: ["secretNames"]

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: gcert-user-requests
    # singular name to be used as an alias on the CLI and for display
    singular: gcert-user-request
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: GCertUserRequest
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - gcrqu
